import { MaterialCommunityIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useState } from "react";
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";

export default function ConnectScreen() {
  const [secure, setSecure] = useState(true);
  const [host, setHost] = useState("");
  const [port, setPort] = useState("8729");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [status, setStatus] = useState("لم يتم اختبار الاتصال بعد");
  const testConnection = trpc.routeros.status.useMutation({ onSuccess: (resource) => setStatus(`تم الاتصال — RouterOS ${resource.version ?? ""}`), onError: (error) => setStatus(`تعذر الاتصال: ${error.message}`) });
  const handleTest = () => { setStatus("جارٍ الاتصال بالراوتر..."); testConnection.mutate({ host: host.trim(), port: Number(port) || (secure ? 8729 : 8728), username: username.trim(), password, tls: secure }); };
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#F8FAFF]" className="px-4">
    <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
      <View style={styles.header}><TouchableOpacity onPress={() => router.back()} style={styles.back}><MaterialCommunityIcons name="arrow-right" size={24} color="#123F95" /></TouchableOpacity><View><Text style={styles.brand}>ALAMEER <Text style={styles.red}>PRO</Text></Text><Text style={styles.caption}>بيانات الاتصال</Text></View><View style={styles.logo}><MaterialCommunityIcons name="router-wireless" size={28} color="white" /></View></View>
      <Text style={styles.title}>إضافة راوتر</Text><Text style={styles.subtitle}>أدخل بيانات RouterOS v6.49.19 للاتصال الفعلي</Text>
      <Field label="عنوان IP أو النطاق" placeholder="مثال: 192.168.88.1" icon="ip-network-outline" value={host} onChangeText={setHost} />
      <View style={styles.row}><View style={{ flex: 1 }}><Field label="المنفذ" placeholder={secure ? "8729" : "8728"} icon="lan-connect" value={port} onChangeText={setPort} keyboardType="numeric" /></View><View style={{ flex: 1 }}><Field label="اسم الاتصال" placeholder="راوتري الرئيسي" icon="router-network" /></View></View>
      <Field label="اسم المستخدم" placeholder="اسم مستخدم RouterOS" icon="account-outline" value={username} onChangeText={setUsername} />
      <Field label="كلمة المرور" placeholder="كلمة المرور" icon="lock-outline" secureTextEntry value={password} onChangeText={setPassword} />
      <TouchableOpacity style={styles.secureRow} onPress={() => { setSecure(!secure); setPort(!secure ? "8729" : "8728"); }}><View style={[styles.switch, secure && styles.switchOn]}><View style={[styles.knob, secure && styles.knobOn]} /></View><View style={{ flex: 1 }}><Text style={styles.secureTitle}>استخدام API-SSL</Text><Text style={styles.secureHint}>موصى به عند الاتصال خارج الشبكة</Text></View><MaterialCommunityIcons name="shield-lock-outline" size={24} color="#1557D8" /></TouchableOpacity>
      <TouchableOpacity style={[styles.primary, testConnection.isPending && { opacity: 0.65 }]} onPress={handleTest} disabled={testConnection.isPending}><MaterialCommunityIcons name={testConnection.isPending ? "loading" : "connection"} size={21} color="white" /><Text style={styles.primaryText}>{testConnection.isPending ? "جارٍ الاتصال..." : "اختبار الاتصال"}</Text></TouchableOpacity>
      <View style={[styles.status, status.startsWith("تم الاتصال") && styles.successStatus, status.startsWith("تعذر") && styles.errorStatus]}><MaterialCommunityIcons name={status.startsWith("تم الاتصال") ? "check-circle-outline" : status.startsWith("تعذر") ? "alert-circle-outline" : "information-outline"} size={22} color={status.startsWith("تم الاتصال") ? "#12833C" : status.startsWith("تعذر") ? "#C52235" : "#9B6B09"} /><Text style={styles.statusText}>{status}</Text></View>
      <TouchableOpacity style={styles.secondary} onPress={() => router.push("/routers" as any)}><Text style={styles.secondaryText}>المتابعة إلى الراوترات المسجلة</Text><MaterialCommunityIcons name="arrow-left" size={21} color="#123F95" /></TouchableOpacity>
    </ScrollView>
  </ScreenContainer>;
}
function Field({ label, placeholder, icon, secureTextEntry, value, onChangeText, keyboardType }: { label: string; placeholder: string; icon: keyof typeof MaterialCommunityIcons.glyphMap; secureTextEntry?: boolean; value?: string; onChangeText?: (value: string) => void; keyboardType?: "numeric" | "default" }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><View style={styles.inputWrap}><MaterialCommunityIcons name={icon} size={21} color="#234C9B" /><TextInput style={styles.input} placeholder={placeholder} placeholderTextColor="#8B9AB4" secureTextEntry={secureTextEntry} textAlign="right" value={value} onChangeText={onChangeText} keyboardType={keyboardType} autoCapitalize="none" /></View></View>; }
const styles = StyleSheet.create({ content: { paddingTop: 10, paddingBottom: 35, gap: 12 }, header: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", backgroundColor: "white", borderRadius: 20, padding: 10, borderWidth: 1, borderColor: "#D5E1F4" }, back: { width: 42, height: 42, borderRadius: 13, backgroundColor: "#F2F6FF", justifyContent: "center", alignItems: "center" }, brand: { color: "#123F95", fontSize: 18, fontWeight: "900", textAlign: "center" }, red: { color: "#E11D34" }, caption: { color: "#65748E", textAlign: "center", fontSize: 11 }, logo: { width: 48, height: 48, borderRadius: 14, backgroundColor: "#114BD0", alignItems: "center", justifyContent: "center" }, title: { color: "#102A62", fontSize: 27, fontWeight: "900", textAlign: "right", marginTop: 12 }, subtitle: { color: "#7C8BA6", fontSize: 13, textAlign: "right", marginBottom: 5 }, field: { gap: 6 }, label: { color: "#183A7E", textAlign: "right", fontSize: 13, fontWeight: "800" }, inputWrap: { height: 53, borderRadius: 15, backgroundColor: "white", borderWidth: 1, borderColor: "#CEDBF0", paddingHorizontal: 14, flexDirection: "row-reverse", alignItems: "center", gap: 9 }, input: { flex: 1, color: "#102A62", fontSize: 14 }, row: { flexDirection: "row-reverse", gap: 10 }, secureRow: { backgroundColor: "#EEF5FF", borderRadius: 16, padding: 12, flexDirection: "row-reverse", alignItems: "center", gap: 10, borderWidth: 1, borderColor: "#C9DCF8" }, switch: { width: 42, height: 24, borderRadius: 15, backgroundColor: "#AAB8CC", padding: 3 }, switchOn: { backgroundColor: "#185DD6" }, knob: { width: 18, height: 18, borderRadius: 10, backgroundColor: "white" }, knobOn: { alignSelf: "flex-end" }, secureTitle: { color: "#123F95", fontWeight: "800", textAlign: "right" }, secureHint: { color: "#71829F", fontSize: 11, textAlign: "right", marginTop: 2 }, primary: { height: 54, backgroundColor: "#1256D8", borderRadius: 16, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 8 }, primaryText: { color: "white", fontWeight: "900", fontSize: 15 }, status: { backgroundColor: "#FFF8E5", borderRadius: 15, padding: 12, flexDirection: "row-reverse", alignItems: "center", gap: 8 }, successStatus: { backgroundColor: "#EAF8EE" }, errorStatus: { backgroundColor: "#FFF0F2" }, statusText: { color: "#795A0B", flex: 1, textAlign: "right", fontSize: 12 }, secondary: { height: 50, borderRadius: 15, backgroundColor: "white", borderWidth: 1, borderColor: "#C5D5EF", flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 8 }, secondaryText: { color: "#123F95", fontWeight: "800" } });
