import { MaterialCommunityIcons } from "@expo/vector-icons";
import { Alert, Modal, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useRouterConnection } from "@/lib/router-context";
import { trpc } from "@/lib/trpc";

export function PowerMenu({ visible, onClose }: { visible: boolean; onClose: () => void }) {
  const { connection } = useRouterConnection();
  const powerMutation = trpc.routeros.power.useMutation({ onSuccess: () => Alert.alert("تم إرسال الأمر", "تم إرسال أمر الطاقة إلى الراوتر."), onError: () => Alert.alert("تعذر تنفيذ الأمر", "تعذر تنفيذ أمر الطاقة. تحقق من الاتصال وصلاحيات RouterOS.") });
  const requestPower = (action: "reboot" | "shutdown") => { onClose(); if (!connection) return Alert.alert("لا يوجد اتصال", "أدخل بيانات الراوتر واختبر الاتصال قبل تنفيذ أمر الطاقة."); powerMutation.mutate({ connection, action }); };
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.modal}><Text style={styles.title}>خيارات الطاقة</Text><Text style={styles.hint}>هذه أوامر فعلية وسيتم تنفيذها على الراوتر المتصل.</Text><TouchableOpacity style={styles.action} onPress={() => requestPower("reboot")}><MaterialCommunityIcons name="restart" size={24} color="#1557D8" /><Text style={styles.actionText}>إعادة تشغيل الراوتر</Text></TouchableOpacity><TouchableOpacity style={[styles.action, styles.shutdown]} onPress={() => requestPower("shutdown")}><MaterialCommunityIcons name="power" size={24} color="#D52239" /><Text style={[styles.actionText, styles.shutdownText]}>إيقاف تشغيل الراوتر</Text></TouchableOpacity><TouchableOpacity style={styles.cancel} onPress={onClose}><Text style={styles.cancelText}>إلغاء</Text></TouchableOpacity></View></View></Modal>;
}
const styles = StyleSheet.create({ backdrop: { flex: 1, backgroundColor: "#071330A8", justifyContent: "center", padding: 20 }, modal: { backgroundColor: "white", borderRadius: 22, padding: 18, gap: 12 }, title: { color: "#102A62", fontFamily: "CairoExtraBold", fontWeight: "900", fontSize: 21, textAlign: "right" }, hint: { color: "#71829F", textAlign: "right", fontSize: 12, lineHeight: 19 }, action: { height: 54, borderRadius: 14, backgroundColor: "#EEF5FF", flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 9 }, shutdown: { backgroundColor: "#FFF0F2" }, actionText: { color: "#1557D8", fontFamily: "CairoExtraBold", fontWeight: "900" }, shutdownText: { color: "#D52239" }, cancel: { height: 46, borderRadius: 13, backgroundColor: "#F3F6FB", justifyContent: "center", alignItems: "center" }, cancelText: { color: "#183A7E", fontFamily: "CairoExtraBold", fontWeight: "800" } });
